name: issues pipeline

on: [issues]

jobs:
    submit-issue:
        runs-on: ubuntu-latest
        steps:
            - name: show error
              run : echo "${{ toJson(github.event.issue) }}" 
             