name: CI/CD pipeline

on: [push,workflow_dispatch]

jobs:
    all-in-one:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v3

            - name: install node
              run : npm ci
                        
            - name: run test
              run:  npm run test

            - name: run linter
              run:  npm run lint

            - name: run build
              run:  npm run build
